AuthorQuery:
    type: object
    config:
        description: "Author"
        fields:
            authors:
                type: "[Author]"
                resolve: "@=query('authors')"
            author:
                type: "Author"
                resolve: "@=query('author', args['id'])"
                args:
                    id:
                        description: "Author id"
                        type: "String!"
