Book:
    type: object
    config:
        description: "Book"
        fields:
            id:
                type: "String!"
                description: "Book id."
            title:
                type: "String!"
                description: "Book title."
            authors:
                type: "[Author]"
                description: "Author list."
            description:
                type: "String"
                description: "Book description."
            publishedYear:
                type: "Int"
                description: "Published year."

CreateBookInput:
    type: input-object
    config:
        fields:
            title:
                type: "String!"
                description: "Book title."
            authors:
                type: "String!"
                description: "Author ids separated by comma, e.g. '0022044f-032b-45b7-8761-efea293628be, 023fab1d-6553-4280-9945-c54c5f105a73'."
            description:
                type: "String"
                description: "Book description."
            publishedYear:
                type: "Int"
                description: "Published year."

UpdateBookInput:
    type: input-object
    config:
        fields:
            id:
                type: "String!"
                description: "Book id."
            title:
                type: "String"
                description: "Book title."
            authors:
                type: "String"
                description: "Author ids separated by comma, e.g. '0022044f-032b-45b7-8761-efea293628be, 023fab1d-6553-4280-9945-c54c5f105a73'."
            description:
                type: "String"
                description: "Book description."
            publishedYear:
                type: "Int"
                description: "Published year."
