BookQuery:
    type: object
    config:
        description: "Book"
        fields:
            books:
                type: "[Book]"
                resolve: "@=query('books', args['input'])"
                args:
                    input:
                        type: "FilterBookInput"
                        description: 'Title, author name and published year.'

            book:
                type: "Book"
                resolve: "@=query('book', args['id'])"
                args:
                    id:
                        description: "Book id"
                        type: "String!"
