overblog_graphql:
    definitions:
        schema:
            author:
                query: AuthorQuery
                mutation: AuthorMutation
            book:
                query: ~
                mutation: ~
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
